// Methods
export const METHOD_GET = 'GET';
export const METHOD_POST = 'POST';
export const METHOD_PUT = 'PUT';

// Get Rooms
export const GET_ROOMS_PENDING = 'GET_ROOMS_PENDING';
export const GET_ROOMS_FULFILLED = 'GET_ROOMS_FULFILLED';
export const GET_ROOMS_REJECTED = 'GET_ROOMS_REJECTED';

// Post a room
export const POST_ROOM_PENDING = 'POST_ROOM_PENDING';
export const POST_ROOM_FULFILLED = 'POST_ROOM_FULFILLED';
export const POST_ROOM_REJECTED = 'POST_ROOM_REJECTED';

// Put a room
export const PUT_ROOM_PENDING = 'PUT_ROOM_PENDING';
export const PUT_ROOM_FULFILLED = 'PUT_ROOM_FULFILLED';
export const PUT_ROOM_REJECTED = 'PUT_ROOM_REJECTED';

// Get Customers
export const GET_CUSTOMERS_PENDING = 'GET_CUSTOMERS_PENDING';
export const GET_CUSTOMERS_FULFILLED = 'GET_CUSTOMERS_FULFILLED';
export const GET_CUSTOMERS_REJECTED = 'GET_CUSTOMERS_REJECTED';

// Post a customer
export const POST_CUSTOMERS_PENDING = 'POST_CUSTOMERS_PENDING';
export const POST_CUSTOMERS_FULFILLED = 'POST_CUSTOMERS_FULFILLED';
export const POST_CUSTOMERS_REJECTED = 'POST_CUSTOMERS_REJECTED';

// Put a customer
export const PUT_CUSTOMERS_PENDING = 'PUT_CUSTOMERS_PENDING';
export const PUT_CUSTOMERS_FULFILLED = 'PUT_CUSTOMERS_FULFILLED';
export const PUT_CUSTOMERS_REJECTED = 'PUT_CUSTOMERS_REJECTED';

// Get checkin
export const GET_CHECKIN_PENDING = 'GET_CHECKIN_PENDING';
export const GET_CHECKIN_FULFILLED = 'GET_CHECKIN_FULFILLED';
export const GET_CHECKIN_REJECTED = 'GET_CHECKIN_REJECTED';

// Post a checkin
export const POST_CHECKIN_PENDING = 'POST_CHECKIN_PENDING';
export const POST_CHECKIN_FULFILLED = 'POST_CHECKIN_FULFILLED';
export const POST_CHECKIN_REJECTED = 'POST_CHECKIN_REJECTED';

// Put a checkin
export const PUT_CHECKIN_PENDING = 'PUT_CHECKIN_PENDING';
export const PUT_CHECKIN_FULFILLED = 'PUT_CHECKIN_FULFILLED';
export const PUT_CHECKIN_REJECTED = 'PUT_CHECKIN_REJECTED';

// Get a profile
export const GET_PROFILE_PENDING = 'GET_PROFILE_PENDING';
export const GET_PROFILE_FULFILLED = 'GET_PROFILE_FULFILLED';
export const GET_PROFILE_REJECTED = 'GET_PROFILE_REJECTED';

// Put a profile
export const PUT_PROFILE_PENDING = 'PUT_PROFILE_PENDING';
export const PUT_PROFILE_FULFILLED = 'PUT_PROFILE_FULFILLED';
export const PUT_PROFILE_REJECTED = 'PUT_PROFILE_REJECTED';

// Reset
export const RESET_ROOMS = 'RESET_ROOMS';
export const RESET_CUSTOMERS = 'RESET_CUSTOMERS';
export const RESET_CHECKIN = 'RESET_CHECKIN';
export const RESET_PAGES = 'RESET_PAGES';
export const RESET_PROFILE = 'RESET_PROFILE';
