const strings = {
  LOGIN: 'L o g i n',
  SIGNUP1: "Don't have an account ? ",
  SIGNUP2: 'Sign up.',
  LOGIN1: 'Already have an account ? ',
  LOGIN2: 'Sign in.',
  REGISTER: 'R e g i s t e r',
  LOGOUT: 'Log Out',
  WELCOME_TO_LOGIN: 'Login',
  WELCOME_TO_REGISTER: 'Register',
  WELCOME_TITLE_APP: 'coHyPe',
  LOADING_TITLE: 'coHyPe',
  LOADING_DESC: 'The future is here ..',
  UNAME_PLACEHOLDER: 'Username',
  EMAIL_PLACEHOLDER: 'Email',
  PASSWORD_PLACEHOLDER: 'Password',
  TRYAGAIN: 'Try Again',
  MODALMSG: 'Sorry, something went wrong.',
  FONT_LOADING: 'Sriracha-Regular',
  FONT: 'JosefinSans-Regular',
  FONT_BOLD: 'JosefinSans-Bold',
  CHECKIN: 'Checkin',
  ROOM: 'Room',
  CUSTOMER: 'Customer',
  SETTING: 'Settings',
  TRYAGAIN: 'Try Again',
  LOADING: 'Loading, please wait ..',
  TIMEOUT: 'Request Timeout',
  CANCEL: 'Cancel',
  SUBMIT: 'Submit',
  ROOMCFG: 'Room',
  CUSTOMERCFG: 'Customer',
  CHKINCFG: 'Checkin',
  RNAME: 'Room Name',
  CNAME: 'Customer Name',
  DURATION: 'Duration (minutes)',
  DURATION2: 'Duration Left (minutes)',
  INPUT_NAME: 'Name',
  INPUT_ID_NUM: 'ID Number',
  INPUT_PHONE_NUM: 'Phone Number',
  DONE: 'DONE',
  SKIP: 'SKIP',
  INTRO_TITLE1: 'Growing space',
  INTRO_TITLE2: 'Awesome feature',
  INTRO_TITLE3: 'User friendly',
  INTRO_DESC1:
    'coHyPe is a growing co-working space management application that will make the life easier.',
  INTRO_DESC2: 'Contain easy but awesome features that will blow your mind.',
  INTRO_DESC3: 'Designed with power of colors, and UI friendly.',
  EMPTY_DATA: "It's empty! Let's create one.",
};

export default strings;
